/*
 * Visier Consolidated Analytics APIs
 * Visier APIs for managing consolidated analytics (CA) tenants.
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConsolidatedAnalyticsAPISourceTenantListDTO
 */
public class ConsolidatedAnalyticsAPISourceTenantListDTOTest {
    private final ConsolidatedAnalyticsAPISourceTenantListDTO model = new ConsolidatedAnalyticsAPISourceTenantListDTO();

    /**
     * Model tests for ConsolidatedAnalyticsAPISourceTenantListDTO
     */
    @Test
    public void testConsolidatedAnalyticsAPISourceTenantListDTO() {
        // TODO: test ConsolidatedAnalyticsAPISourceTenantListDTO
    }

    /**
     * Test the property 'tenantCodes'
     */
    @Test
    public void tenantCodesTest() {
        // TODO: test tenantCodes
    }

}
